### ISSUE TITLE
Bug interface en 2560*1440

### ISSUE THREAD

**Issue by Camisang** [Calvitix/CalmodPack#1]
Bonjour Calvitix,
L'interface ne fonctionne pas correctement à la résolution 2560*1440, les icônes de messages se retrouvent cacher par l'interface de jeu.
![Bug_Interface](https://user-images.githubusercontent.com/82241929/114245318-8a537e00-9990-11eb-9d76-0ced238cd12a.png)

**Comment by Camisang** [comment]
En fait c'est l'affichage des 7 ressources rares + la case vide qui vient allonger l'interface. 
Quelle est la méthode pour corriger ça ?

**Comment by Calvitix** [comment]
Salut, je viens de mettre en ligne une version qui devrait corriger tout cela. Cela se situe dans le fichier 'interface/main_alerts.gui'. 
Il faut retirer les dispositions spécifiques pour cette résolution.

**Comment by Camisang** [comment]
Bonjour Calvitix,
J'ai essayé cette nouvelle version et tout fonctionne parfaitement désormais 👍
Merci pour la mise à jour !

**Comment by Calvitix** [comment]
ok, merci pour le retour. Je clos le ticket
